spring.application.name=votacao

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/votacao}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.cache.type: redis
spring.data.redis.host: ${REDIS_HOST:localhost}
spring.data.redis.port: ${REDIS_PORT:6379}

server.port=8080